### Session Creation
- Limit rate of creation requests
- Any application shall not exceed 5 concurrent session requests per second
- Limit number of concurrent active sessions
- Any application shall not exceed 10 concurrent active sessions
### Search and Retrieve
- Limit rate of search requests
- Any application shall not exceed 100 search requests per second per session
- Limit rate of retrieve requests
- Any application shall not exceed 100 retrieve requests per second per session
### Resultsets
- Limit number of resultsets
- Any application shall not exceed 500 resultsets per session

## In Carl language
1. Just request one session
2. Just have one active session
3. Don't do lots of searches/retrievals automated/parallized
4. Don't do to many retrievals, otherwise start new session

Build in something that print out number of retrievels at each retrieval

In [2]:
session_activations = 0
search_and_retrieve_requests = 0
number_of_resultssets = 0

In [10]:
from Reaxys_API import Reaxys_API

structure_v2000 = """structure('

HDR
 14 14  0  0  1  0  0  0  0  0999 V2000
    1.6722    0.9384    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7056    1.1977    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1713    1.8045    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3300    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.4904    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4480    2.1643    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.1715    1.8045    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6724    2.6705    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6724    0.9384    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6708    2.6705    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6708    0.9384    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.1717    1.8045    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.1736    1.8045    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.5788    0.5151    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  1  4  1  0  0  0  0
  1 14  1  1  0  0  0
  2  5  1  0  0  0  0
  2  6  2  0  0  0  0
  3  7  1  0  0  0  0
  7  8  2  0  0  0  0
  7  9  1  0  0  0  0
  8 10  1  0  0  0  0
  9 11  2  0  0  0  0
 10 12  2  0  0  0  0
 11 12  1  0  0  0  0
 12 13  1  0  0  0  0
M  REG 392441
M  END
','exact,tautomers,no_extra_rings')"""
def example_2(ra,search_and_retrieve_requests, number_of_resultssets):
    ra.select("RX", "R", structure_v2000, "", "WORKER,NO_CORESULT")
    response = ra.retrieve(
        ra.resultname,
        ["RY"], "1", "1", "", "", "", "ISSUE_RXN=true,ISSUE_RCT=false")
    results = ra.get_field_content(response, "RY.STR")
    for i in results:
        print(i)
    number_of_resultssets += 1
    search_and_retrieve_requests += 1
    print("Number of results sets: ", number_of_resultssets)
    print("Search and retrieve requests: ", search_and_retrieve_requests)
cas_ids = ["64-18-6", "64-19-7", "64-67-5"]
def example_1(ra,search_and_retrieve_requests,number_of_resultssets):
    for cas_id in cas_ids:
        ra.select("RX", "S", "IDE.RN = '" + cas_id + "'", "",
                  "WORKER,NO_CORESULT")
        if ra.resultsize != 0:
            response = ra.retrieve(ra.resultname, ["MP"], str(1),
                                   str(ra.resultsize), "", "", "", "")
            results = ra.get_field_content(response, "MP.MP")
            for r in results:
                datapoint = cas_id + "\t" + r + "\n"
                print(datapoint)
    number_of_resultssets += 1
    search_and_retrieve_requests += 1
    print("Number of results sets: ", number_of_resultssets)
    print("Search and retrieve requests: ", search_and_retrieve_requests)

In [3]:
API_URL = 'https://www.reaxys.com/reaxys/api'
user = ''
pw = ''
callername = 'ETH_june2018'
api = Reaxys_API()
api.connect(API_URL, '', user, pw, callername)
session_activations += 1

In [9]:
example_2(api,search_and_retrieve_requests, number_of_resultssets)

$RXN V3000

  Mrv17d0      112401231233

M  V30 COUNTS 3 1
M  V30 BEGIN REACTANT
M  V30 BEGIN CTAB
M  V30 COUNTS 3 2 0 0 0 REGNO=102415
M  V30 BEGIN ATOM
M  V30 1 N -24.8606 0.0513 0 0
M  V30 2 N -23.3204 0.0513 0 0
M  V30 3 C -26.4004 0.0513 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 3 1 2
M  V30 2 2 1 3
M  V30 END BOND
M  V30 END CTAB
M  V30 BEGIN CTAB
M  V30 COUNTS 13 13 0 0 0 REGNO=515881
M  V30 BEGIN ATOM
M  V30 1 C -17.4902 -0.6669 0 0
M  V30 2 C -19.0304 -0.6669 0 0
M  V30 3 C -16.7202 0.6669 0 0
M  V30 4 N -16.7202 -2.0004 0 0
M  V30 5 O -19.8004 -2.0004 0 0
M  V30 6 O -19.8004 0.6669 0 0
M  V30 7 C -15.1804 0.6669 0 0
M  V30 8 C -14.4101 2.0004 0 0
M  V30 9 C -14.4101 -0.6669 0 0
M  V30 10 C -12.8702 2.0004 0 0
M  V30 11 C -12.8702 -0.6669 0 0
M  V30 12 C -12.1003 0.6669 0 0
M  V30 13 O -10.56 0.6669 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 1 3
M  V30 3 1 1 4
M  V30 4 1 2 5
M  V30 5 2 2 6
M  V30 6 1 3 7
M  V30 7 1 7 8
M  V30 8 2 7 9
M  V30 9 2 8 10
M  V30 10 1 9 11
M  V30 11 1 10 12
M  V30 12 2 11 12
M  V30 13 1 12 13
M  V30 END BOND
M  V30 END CTAB
M  V30 BEGIN CTAB
M  V30 COUNTS 3 2 0 0 0 REGNO=102415
M  V30 BEGIN ATOM
M  V30 1 N -4.6202 0.0513 0 0
M  V30 2 N -3.08 0.0513 0 0
M  V30 3 C -6.16 0.0513 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 3 1 2
M  V30 2 2 1 3
M  V30 END BOND
M  V30 END CTAB
M  V30 END REACTANT
M  V30 BEGIN PRODUCT
M  V30 BEGIN CTAB
M  V30 COUNTS 15 15 0 0 0 REGNO=2808649
M  V30 BEGIN ATOM
M  V30 1 C 12.0999 0.6669 0 0
M  V30 2 C 10.56 0.6669 0 0
M  V30 3 C 12.8702 2.0004 0 0
M  V30 4 C 12.8702 -0.6669 0 0
M  V30 5 C 9.79 -0.6669 0 0
M  V30 6 C 14.4101 2.0004 0 0
M  V30 7 C 14.4101 -0.6669 0 0
M  V30 8 C 8.2499 -0.6669 0 0
M  V30 9 N 10.56 -2.0004 0 0
M  V30 10 C 15.1799 0.6669 0 0
M  V30 11 O 7.4799 -2.0004 0 0
M  V30 12 O 7.4799 0.6669 0 0
M  V30 13 O 16.7202 0.6669 0 0
M  V30 14 C 5.94 -2.0004 0 0
M  V30 15 C 17.4901 -0.6669 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 1 3
M  V30 3 2 1 4
M  V30 4 1 2 5
M  V30 5 2 3 6
M  V30 6 1 4 7
M  V30 7 1 5 8
M  V30 8 1 5 9
M  V30 9 1 6 10
M  V30 10 2 7 10
M  V30 11 1 8 11
M  V30 12 2 8 12
M  V30 13 1 10 13
M  V30 14 1 11 14
M  V30 15 1 13 15
M  V30 END BOND
M  V30 END CTAB
M  V30 END PRODUCT
M  END

Number of results sets:  1
Search and retrieve requests:  1

In [11]:
example_1(api,search_and_retrieve_requests, number_of_resultssets)

64-18-6	8.4

64-19-7	16.7

64-19-7	156.6

64-67-5	-25

Number of results sets:  1
Search and retrieve requests:  1

In [14]:
#read in xls file
import pandas as pd
df = pd.read_excel('Reaxys_database_fields_v2.0.004.xlsx', sheet_name='Sheet1')
df.head()

,Item No,Subject/Name,Name,Code,Unit,Context,Searchtype,Available for,Output,Description,Example,Tips and Hints,Searchable,Referenced Field,RMC Flat File Node [attribute],UDM v5 Field [attribute],UDM v4 Field [attribute]
0,1,Field Availability,Field Availability,FA,NaN,NaN,NaN,NaN,"SD, Excel, XML, API",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Field Availability,"Field Availability (see sheet ""Substance facts"")",FA.FA,NaN,S,S,"RX, RMC, combined","SD, Excel, XML, API",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Reaction Availability,Reaction Availability,RA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Reaction Availability,Reaction Availability,RA.RA,NaN,R,S,"RX, combined",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Citation Availability,Citation Availability,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
spreadsheet_file = pd.ExcelFile('Reaxys_database_fields_v2.0.004.xlsx')
worksheets = spreadsheet_file.sheet_names

In [17]:
worksheets

['Fields',
 'Field Units',
 'Substance facts',
 'Query syntax',
 'Remarks',
 'Version']

In [31]:
df_fields = pd.read_excel(spreadsheet_file, sheet_name='Fields')
df_fields_units = pd.read_excel(spreadsheet_file, sheet_name='Field Units')
df_substance_facts = pd.read_excel(spreadsheet_file, sheet_name='Substance facts')
df_query_syntax = pd.read_excel(spreadsheet_file, sheet_name='Query syntax')
df_remarks = pd.read_excel(spreadsheet_file, sheet_name='Remarks')
df_version = pd.read_excel(spreadsheet_file, sheet_name='Version')

In [46]:
# descriptions = df_substance_facts['Description'].tolist()
# [n for n in descriptions if 'vapor' in n.lower() or 'pressure' in n.lower()]

df_fields['Name']

,Item No,Subject/Name,Name,Code,Unit,Context,Searchtype,Available for,Output,Description,Example,Tips and Hints,Searchable,Referenced Field,RMC Flat File Node [attribute],UDM v5 Field [attribute],UDM v4 Field [attribute]
0,1,Field Availability,Field Availability,FA,NaN,NaN,NaN,NaN,"SD, Excel, XML, API",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Field Availability,"Field Availability (see sheet ""Substance facts"")",FA.FA,NaN,S,S,"RX, RMC, combined","SD, Excel, XML, API",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Reaction Availability,Reaction Availability,RA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Reaction Availability,Reaction Availability,RA.RA,NaN,R,S,"RX, combined",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Citation Availability,Citation Availability,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1777,1778,Bioactivity Target Ids (RMC),Target ID,DATIDS.TID,NaN,DPI,R,"RMC, combined, RMC FF","XML, API",target object technical identifier,<number>,NaN,NaN,NaN,"rdf:Description [rdf:about=""Target/#xxxx""]",NaN,NaN
1778,1779,Bioactivity Target Ids (RMC),Target Subunit Synonyms,DATIDS.TSUBSYN,NaN,DPI,S,"RMC, combined, RMC FF","XML, API",protein/target name synonyms (from Reaxys taxo...,NaN,NaN,NaN,NaN,fct:SUBSYNONYM,NaN,NaN
1779,1780,Bioactivity Target Ids (RMC),Target Uniprot ID,DATIDS.TUNIPROT,NaN,DPI,S,"RMC, combined, RMC FF","XML, API",protein/target external Ids :UNIPROT,NaN,NaN,NaN,NaN,uniprot:TUNIPROT,NaN,NaN
1780,1781,Bioactivity Target Ids (RMC),Target PDB ID,DATIDS.TPDB,NaN,DPI,S,"RMC, combined, RMC FF","XML, API",protein/target external Ids :PDB,NaN,NaN,NaN,NaN,pdb:TPDB,NaN,NaN
1781,1782,Bioactivity Target Ids (RMC),Target Concept ID,DATIDS.TUID,NaN,DPI,S,"RMC, combined, RMC FF","XML, API",RMC taxonomy concept UID,<number>,NaN,NaN,NaN,fct:SUBUID,NaN,NaN

In [26]:
df_fields = pd.read_excel(spreadsheet_file, sheet_name='Field Units')
field_names = df_fields['Field Name'].tolist()

In [28]:
df_fields[df_fields['Field Name'] == 'Vapour Pressure']

          Field Name Field Code Field Unit
130  Vapour Pressure      VP.VP       Torr

In [38]:
df_fields_units[df_fields_units['Field Name'] == 'Melting Point']

      Field Name Field Code Field Unit
5  Melting Point      MP.MP         °C

In [62]:
# df_fields_units[df_fields_units['Field Name'] == 'Temperature'].head(50)
df_fields_units[df_fields_units['Field Code'] == 'VP.T']

      Field Name Field Code Field Unit
131  Temperature       VP.T         °C

In [24]:
field_names_vapor_pressure = [n for n in field_names if 'vapor' in n.lower() or 'pressure' in n.lower()]
field_names_vapor_pressure

['Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Critical Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Enthalpy of Vaporization',
 'Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Pressure',
 'Vapour Pressure',
 'Pressure']

In [65]:
def retrieve_vp_from_cas(ra,search_and_retrieve_requests,number_of_resultssets,cas_ids):
    for cas_id in cas_ids:
        ra.select("RX", "S", "IDE.RN = '" + cas_id + "'", "",
                  "WORKER,NO_CORESULT")
        if ra.resultsize != 0:
            response = ra.retrieve(ra.resultname, ["VP"], str(1),
                                   str(ra.resultsize), "", "", "", "")
            results = ra.get_field_content(response, "VP.VP")
            for r in results:
                # datapoint = cas_id + "\t" + r + "\n"
                print(f'CAS: {cas_id} has vapor pressur of {r} Torr')
    number_of_resultssets += 1
    search_and_retrieve_requests += 1
    print("Number of results sets: ", number_of_resultssets)
    print("Search and retrieve requests: ", search_and_retrieve_requests)
    return search_and_retrieve_requests, number_of_resultssets,results

def get_vp_and_temp_from_cas(ra, search_and_retrieve_requests, number_of_resultssets, cas_ids):
    results = []
    for cas_id in cas_ids:
        ra.select("RX", "S", "IDE.RN = '" + cas_id + "'", "", "WORKER,NO_CORESULT")
        if ra.resultsize != 0:
            response = ra.retrieve(ra.resultname, ["VP"], str(1), str(ra.resultsize), "", "", "", "")
            vp_results = ra.get_field_content(response, "VP.VP")
            vp_tmp = ra.get_field_content(response, "VP.T")
            for vp, t in zip(vp_results, vp_tmp):
                results.append((cas_id, vp, t))
                print(f"CAS: {cas_id} has vapor pressure of {vp} Torr at temperature {t} K")
    number_of_resultssets += 1
    search_and_retrieve_requests += 1
    print("Number of result sets: ", number_of_resultssets)
    print("Search and retrieve requests: ", search_and_retrieve_requests)
    return search_and_retrieve_requests, number_of_resultssets, results

In [67]:
ra = api
cas_id = "71-43-2"
ra.select("RX", "S", "IDE.RN = '" + cas_id + "'", "","WORKER,NO_CORESULT")
print(ra.resultsize)

6

In [68]:
ra.resultname

'H021__2286511006823139256'

In [51]:
search_and_retrieve_requests, number_of_resultssets,results = retrieve_vp_from_cas(api,search_and_retrieve_requests, number_of_resultssets,cas_ids = ["27676-62-6","1076-43-3","71-43-2"])
results

CAS: 1076-43-3 has vapor pressur of 280.395 - 37351.9 Torr
CAS: 71-43-2 has vapor pressur of 148.152 - 498.572 Torr
Number of results sets:  4
Search and retrieve requests:  4

['148.152 - 498.572']

In [66]:
search_and_retrieve_requests, number_of_resultssets,results = get_vp_and_temp_from_cas(api,search_and_retrieve_requests, number_of_resultssets,cas_ids = ["27676-62-6","1076-43-3","71-43-2"])
results

CAS: 1076-43-3 has vapor pressure of 280.395 - 37351.9 Torr at temperature 50.2 - 287.1 K
CAS: 71-43-2 has vapor pressure of 148.152 - 498.572 Torr at temperature 35.04 - 67.02 K
Number of result sets:  6
Search and retrieve requests:  6

[('1076-43-3', '280.395 - 37351.9', '50.2 - 287.1'),
 ('71-43-2', '148.152 - 498.572', '35.04 - 67.02')]

In [52]:
ra = api
cas_id = "71-43-2"
ra.select("RX", "S", "IDE.RN = '" + cas_id + "'", "","WORKER,NO_CORESULT")
response = ra.retrieve(ra.resultname, ["VP"], str(1),
                                   str(ra.resultsize), "", "", "", "")
results = ra.get_field_content(response, "VP.VP")
number_of_resultssets += 1
search_and_retrieve_requests += 1
print("Number of results sets: ", number_of_resultssets)
print("Search and retrieve requests: ", search_and_retrieve_requests)

Number of results sets:  5
Search and retrieve requests:  5

In [54]:
response

'<?xml version=\'1.0\' encoding=\'UTF-8\'?><xf><request sessionid="-2286511006823139256" caller="ETH_june2018"><statement command="select"/><select_list><select_item>VP</select_item></select_list><from_clause first_item="1" last_item="6" resultname="H015__2286511006823139256"/><group_by_clause/><order_by_clause/><options/></request>\n<response version="1.0.892-nonprod2"><status>OK</status><message>0.005 sec</message><results>\n<result>\n  <resultname>H015__2286511006823139256</resultname>\n  <resultsize>6</resultsize>\n  <dbname>RX230721RX</dbname>\n  <context>substances</context>\n  <created>2023-11-24:13:11:10.546</created>\n  <comment>saved 2023-11-24:13:11:10.546</comment>\n  <where_clause>IDE.RN = &apos;71-43-2&apos;</where_clause>\n</result>\n</results></response>\n  <substances>\n    <substance index="1">\n      <VP>\n        <VP.L>6375140</VP.L>\n        <VP.VP>148.152 - 498.572</VP.VP>\n        <VP.T>35.04 - 67.02</VP.T>\n        <VP.ED>2007/10/05</VP.ED>\n        <citations>\n          <citation index="1">\n            <CNR>\n              <CNR.CNR>6375140</CNR.CNR>\n              <CNR.CED>2007/10/03</CNR.CED>\n              <CNR.CUPD>2016/06/28</CNR.CUPD>\n            </CNR>\n            <CIT>\n              <CIT.DT>Article</CIT.DT>\n              <CIT.AU>Lubomska, Monika; Banas, Agnieszka; Malanowski, Stanislaw K.</CIT.AU>\n              <CIT.ABPR>Y</CIT.ABPR>\n              <CIT.IMPACT>2.196</CIT.IMPACT>\n              <CIT.PREPY>2002</CIT.PREPY>\n              <CIT.PUI>35420270</CIT.PUI>\n              <CIT.PS>published</CIT.PS>\n              <CIT.IS>manual</CIT.IS>\n              <CIT01>\n                <CIT.CO>JCEAA</CIT.CO>\n                <CIT.JT>Journal of Chemical and Engineering Data</CIT.JT>\n                <CIT.JTS>J. Chem. Eng. Data</CIT.JTS>\n                <CIT.CC>usa</CIT.CC>\n                <CIT.LA>English</CIT.LA>\n                <CIT.PUB>American Chemical Society</CIT.PUB>\n                <CIT.VL>47</CIT.VL>\n                <CIT.NB>6</CIT.NB>\n                <CIT.PY>2002</CIT.PY>\n                <CIT.PAG>1466 - 1471</CIT.PAG>\n                <CIT.DOI>10.1021/je025540l</CIT.DOI>\n                <CIT.ISSN>0021-9568</CIT.ISSN>\n                <CIT.SCOPUS>0036827368</CIT.SCOPUS>\n                <CIT.CITBY>8</CIT.CITBY>\n              </CIT01>\n              <CIT.DOCQ>0.7</CIT.DOCQ>\n            </CIT>\n          </citation>\n        </citations>\n      </VP>\n    </substance>\n  </substances>\n  <citations>\n    <citation index="1">\n      <CNR>\n        <CNR.CNR>6375140</CNR.CNR>\n        <CNR.CED>2007/10/03</CNR.CED>\n        <CNR.CUPD>2016/06/28</CNR.CUPD>\n      </CNR>\n      <CIT>\n        <CIT.DT>Article</CIT.DT>\n        <CIT.AU>Lubomska, Monika; Banas, Agnieszka; Malanowski, Stanislaw K.</CIT.AU>\n        <CIT.ABPR>Y</CIT.ABPR>\n        <CIT.IMPACT>2.196</CIT.IMPACT>\n        <CIT.PREPY>2002</CIT.PREPY>\n        <CIT.PUI>35420270</CIT.PUI>\n        <CIT.PS>published</CIT.PS>\n        <CIT.IS>manual</CIT.IS>\n        <CIT01>\n          <CIT.CO>JCEAA</CIT.CO>\n          <CIT.JT>Journal of Chemical and Engineering Data</CIT.JT>\n          <CIT.JTS>J. Chem. Eng. Data</CIT.JTS>\n          <CIT.CC>usa</CIT.CC>\n          <CIT.LA>English</CIT.LA>\n          <CIT.PUB>American Chemical Society</CIT.PUB>\n          <CIT.VL>47</CIT.VL>\n          <CIT.NB>6</CIT.NB>\n          <CIT.PY>2002</CIT.PY>\n          <CIT.PAG>1466 - 1471</CIT.PAG>\n          <CIT.DOI>10.1021/je025540l</CIT.DOI>\n          <CIT.ISSN>0021-9568</CIT.ISSN>\n          <CIT.SCOPUS>0036827368</CIT.SCOPUS>\n          <CIT.CITBY>8</CIT.CITBY>\n        </CIT01>\n        <CIT.DOCQ>0.7</CIT.DOCQ>\n      </CIT>\n    </citation>\n  </citations>\n</xf>'

In [56]:
ra.resultsize

'6'

In [57]:
for r in results:
    print(f'CAS: {cas_id} has vapor pressur of {r} Torr')

CAS: 71-43-2 has vapor pressur of 148.152 - 498.572 Torr

In [ ]:
# results2 = ra.get_field_content(response, "VP.VP")

In [55]:
results

['148.152 - 498.572']